### ISSUE TITLE
no produce a _HVID_STATE_

### ISSUE THREAD

**Issue by aaguerra** [hdiv/hdiv#101]
@Autowired
ServletContext servletContext;
@Autowired
private HttpServletRequest request; 

LinkUrlProcessor lup = HDIVUtil.getLinkUrlProcessor(servletContext);
RequestContextHolder rch =HDIVUtil.getRequestContext(request);
String processedWithPath = lup.processUrl(rch, "/test" + 1);

System.out.println("processedWithPath-------"+processedWithPath);
//This produce a _HVID_STATE_ but query param always 0
String processedWithQuery = lup.processUrl(rch, "/test?id=" + 1);
System.out.println("processedWithQuery-------"+processedWithQuery);

Result:
processedWithPath-------/test1
processedWithQuery-------/test?id=1

**Comment by gillarramendi** [comment]
`/test` is an absolute url.
If the application has a context path different from `/` the url is linking an external resource, so no  HDIV_STATE is created.
Try adding the context path to the url or using a relative url, like `test`

**Comment by aaguerra** [comment]
Thanks, and this worked
