### ISSUE TITLE
memory pattern clarity

### ISSUE THREAD

**Issue by adamjhamer** [hdiv/hdiv#28]
The StateUtil.java currently has:
`private static final String MEMORY_PATTERN = "([0-9]+-){2}[A-Za-z0-9]+";`

For consistency with the other code it should read:
`private static final String MEMORY_PATTERN = "([0-9]+"+AbstractDataComposer.DASH+"){2}[A-Za-z0-9]+";`

The matching of `[A-Za-z0-9]` assumes that the pluggable uidGenerator will return that format but there is no contract for that. The comment in `AbstractDataComposer.initPage` suggests to take the return value and ensure/convert it to a hex value, but a more OO approach to StateUtil would be better.

**Comment by gillarramendi** [comment]
Only the memory Strategy in supported in Community edition. I'm closing this issue.
Thanks for the suggestion.
