### ISSUE TITLE
maximum client-payload-size is hardwired to 4kb

### ISSUE THREAD

**Issue by MichiShyGuy** [hdiv/hdiv#38]
Hey there,

I know, this might not be a 'real' bug, but I want to push this into consideration for near future development:
Currently the maximum cache size ist hardwired to 4000 bytes. [ConfigBeanDefinition.createDataComposerFactory():306 in current Version 69e41f2]

It would be helpful if this was configurable.

Cheers,
MezzoMicks

**Comment by gillarramendi** [comment]
You can override the default DataComposerFactory bean configuration adding this xml in your hdiv-config.xml file:

```xml
<bean id="org.hdiv.dataComposer.DataComposerFactory" class="org.hdiv.dataComposer.DataComposerFactory">
	<property name="config" ref="org.hdiv.config.HDIVConfig" />
	<property name="session" ref="org.hdiv.session.ISession" />
	<property name="uidGenerator" ref="org.hdiv.idGenerator.UidGenerator" />
	<property name="encodingUtil" ref="org.hdiv.util.EncodingUtil" />
	<property name="stateUtil" ref="org.hdiv.state.StateUtil" />
	<property name="stateScopeManager" ref="org.hdiv.state.scope.StateScopeManager" />
	<!-- Your custom allowed length -->
	<property name="allowedLength" ref="3000" />
</bean>
```
