### ISSUE TITLE
Input validation inprovements for XSS

### ISSUE THREAD

**Issue by emacarron** [hdiv/hdiv#66]
Though HDIV main focus is not preventing XSS we found it quite useful for it.

You would probably know that the most spread anti-XSS library in Java is (ESAPI) [https://github.com/ESAPI/esapi-java]. And I think they have some ideas that are worth considering.

ESAPI strategy for XSS is:
- filter input (Validator)
- encode output (Encoder)

Encoding is not HDIV business (unless you want to cover this also to avoid dependencies).

Input validation is not always possible because sometimes you need to allow "dangerous" characteres. Nervertheless it is still interesting for several reasons:
- It is not a good idea letting malicious data go into your database.
- Input validation can be centralized so the developer starts with a better security by default

ESAPI only applies white list validations that are based on java regular expressions. It can also provide canonicalization (let's talk about it later).

At glance, ESAPI is used like this:
```java
  @org.junit.Test
  public void testValidation() {
    Validator instance = ESAPI.validator();
    Assert.assertTrue(instance.isValidInput("test", "eduardo.macarron@mail.com", "Email", 100, false));       
  }
```

Original code at
https://github.com/emacarron/esapi-input-validation-sample/blob/master/src/test/java/test/Test.java

In the sample avobe, the 3rd parameter "Mail" specifies the type of that input, and the type is matched against one of the rules in validation.properties file:
```
Validator.Email=^[A-Za-z0-9._%'-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$
```
If you go with black lists you can probably have one set of rules for all your inputs (like an application firewall would do) but if you go with white list you need a finer configuration. Right now HDIV only provides one rule for an entire URL, it will be good to be available to set a rule for an specific field. 

The question may be: are we turning HDIV into a general validation framework like a "JSR-303 for Spring MVC" or the old apache validator based on XML?

Our strategy is not using HDIV for validation but only to restrict the allowed characteres for the whole application in a single point. The problem now is that if we find a single field that requires a "<" we have to accept it for all of the fields in that URL.

OTOH ESAPI provides canonicalization but honeslty I still don't know if it is useful or not when using a Java server.

**Comment by gillarramendi** [comment]
Added new attribute 'parameters' in this commit: https://github.com/hdiv/hdiv/commit/08f44637e673862affb4cb49efa8e2e62ef414c5

Now it is possible to configure something like this:
```xml
<hdiv:editableValidations registerDefaults="true">
    <hdiv:validationRule url="/example/form.html" parameters="name, description">customValidation</hdiv:validationRule>
</hdiv:editableValidations>
```

Applying 'customValidation' rule only to 'name' and 'description' parameters.
