### ISSUE TITLE
Feature request: F5 key support (reloading the same page)

### ISSUE THREAD

**Issue by emacarron** [hdiv/hdiv#67]
When using the memory strategy you can only go X pages back until you get to a point where the is no state (it was removed to save memory).

An annoying side effect is that, with 5 pages in memory, when you press F5 five times you get redirected to the error page.

We wonder if HDIV could detect a re-submit so instead of evicting the oldest page it evicts the one that has become unreachable. Let me explain it in detail:

Suppose we have P1, P2, P3, P4, P5 in memory. If we click on a link, P6 wil be created and P1 will be evicted. Queue will be P2, P3, P4, P5, P6.

When pressing F5, the same thing happens. 

So I wonder if HDIV could detect that the page that is being requested comes from an "old link" (P4) and instead of rolling the queue, remove the newer P5 that is no longer reacheable and generate a new one so the queue will end up being: P1, P2, P3, P4, P6.

This can also be applied to older pages. If a user presses back then P4 and P5 will be unreachable so que queue will look like P1, P2, P3, P6.

I made a quick and dirty change in a fork (you can see the changes by clicking in the link Github shows below this comment). At a first sight it seems to work. This is the log while pressing F5.

```
...
[org.hdiv.session.SessionHDIV] - <Getting page with id:68>
[org.hdiv.session.StateCache] - <Deleted pages with id [[77]].>
[org.hdiv.session.StateCache] - <Page with [78] added to the cache. Cache contains [[63, 67, 68, 78]]>
[org.hdiv.session.SessionHDIV] - <Getting page with id:68>
[org.hdiv.session.StateCache] - <Deleted pages with id [[78]].>
[org.hdiv.session.StateCache] - <Page with [79] added to the cache. Cache contains [[63, 67, 68, 79]]>
[org.hdiv.session.SessionHDIV] - <Getting page with id:68>
[org.hdiv.session.StateCache] - <Deleted pages with id [[79]].>
[org.hdiv.session.StateCache] - <Page with [80] added to the cache. Cache contains [[63, 67, 68, 80]]>
...
```
And this is the log if you go two links back:
```
...
[org.hdiv.session.StateCache] - <Page with [87] added to the cache. Cache contains [[67, 68, 85, 86, 87]]>
[org.hdiv.session.SessionHDIV] - <Getting page with id:85>
[org.hdiv.session.StateCache] - <Deleted pages with id [[87, 86]].>
[org.hdiv.session.StateCache] - <Page with [88] added to the cache. Cache contains [[67, 68, 85, 88]]>
...
```

**Comment by gillarramendi** [comment]
Merged into master: https://github.com/hdiv/hdiv/commit/c8d187b9c524003e1315c805266d57b0104d0056

Thanks!
