### ISSUE TITLE
Getting issue with HDIV

### ISSUE THREAD

**Issue by pshah4u** [hdiv/hdiv#68]
Hi i am using hdiv with spring MVC as mention in hdiv reference

for accessing every page i need to put url pattern in start pages and working fine than and log is getting printed as mentioned below

INFO: INVALID_EDITABLE_VALUE;/School/manageAdmission/addApplicantDetails;hissaNoText;*;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser
Dec 30, 2014 4:11:41 PM org.hdiv.logs.Logger log
INFO: INVALID_EDITABLE_VALUE;/School/manageReport/addApplicantDetails;surnocNoText;*;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser

Is this the right way of using hdiv, Please suggest

**Comment by gillarramendi** [comment]
Hi, 
don't put every url in start page, only home page and another exceptional cases, otherwise you are not validating any request.
Keep in mind that you have to create link and forms elements using Spring MVC tags, in order to be processed by HDIV.

Relating to INVALID_EDITABLE_VALUE message, it is created by the editable data validation:
http://hdiv.org/hdiv-documentation-single/doc.html#configuration-editabledata 

It looks like 'hissaNoText' and 'surnocNoText' parameters contains non-accepted characters.

**Comment by pshah4u** [comment]
Hi Thanks for reply. Still not running at all given logs as

INFO: HDIV_PARAMETER_NOT_EXISTS;/Bhoomi/manageMutation/searchSurvey;1457468506;null;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser

My jsp has link as 

<li><a href="<spring:url value="/manageMutation/searchSurvey?ft=mp"/>">Link1</a></li>
<li><a href="<c:url value="/manageMutation/searchSurvey?ft=mp"/>">Link2</a></li>

webmvc-config.xml 

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aop="http://www.springframework.org/schema/aop"
	xmlns:task="http://www.springframework.org/schema/task"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd                 
http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd                 
http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.1.xsd
http://www.springframework.org/schema/aop 
http://www.springframework.org/schema/aop/spring-aop-3.1.xsd
http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task-3.0.xsd
">
	<task:annotation-driven />

	
	 
<mvc:annotation-driven validator="hdivEditableValidator"/>

	<context:property-placeholder location="WEB-INF/spring/*.properties" />

	
	<mvc:resources location="/, classpath:/META-INF/web-resources/"
		mapping="/resources/**" cache-period="${RESOURCE_CACHE_PERIOD}" />

	
	<mvc:default-servlet-handler />

	
	<mvc:interceptors>
		<bean class="org.springframework.web.servlet.theme.ThemeChangeInterceptor" />
		<bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"
			p:paramName="lang" />
	</mvc:interceptors>

	
	<mvc:view-controller path="/" view-name="index" />
	<mvc:view-controller path="/uncaughtException" />
	<mvc:view-controller path="/resourceNotFound" />
	<mvc:view-controller path="/dataAccessFailure" />

	
	<bean
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource"
		id="messageSource"
		p:basenames="classpath:com/accenture/bhoomi/resources/messages,WEB-INF/i18n/application"
		p:fallbackToSystemLocale="false" />

	
	<bean class="org.springframework.web.servlet.i18n.CookieLocaleResolver"
		id="localeResolver" p:cookieName="locale" />

	
	<bean
		class="org.springframework.ui.context.support.ResourceBundleThemeSource"
		id="themeSource" />

	
	<bean class="org.springframework.web.servlet.theme.CookieThemeResolver"
		id="themeResolver" p:cookieName="theme" p:defaultThemeName="standard" />

	
	<bean
		class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver"
		p:defaultErrorView="uncaughtException">
		<property name="exceptionMappings">
			<props>
				<prop key=".DataAccessException">dataAccessFailure</prop>
				<prop key=".NoSuchRequestHandlingMethodException">resourceNotFound</prop>
				<prop key=".TypeMismatchException">resourceNotFound</prop>
				<prop key=".MissingServletRequestParameterException">resourceNotFound</prop>
			</props>
		</property>
	</bean>

	
	
	<bean class="org.springframework.web.servlet.view.UrlBasedViewResolver"
		id="tilesViewResolver">
		<property name="viewClass"
			value="org.springframework.web.servlet.view.tiles2.TilesView" />
	</bean>
	<bean class="org.springframework.web.servlet.view.tiles2.TilesConfigurer"
		id="tilesConfigurer">
		<property name="definitions">
			<list>
				<value>/WEB-INF/layouts/layouts.xml</value>
				
				<value>/WEB-INF/views/**/views.xml</value>
			</list>
		</property>
	</bean>

	<context:annotation-config />
	<context:component-scan base-package="com.accenture.bhoomi" />
	<context:spring-configured />

	<bean id="logAspect" class="com.accenture.bhoomi.aspect.LoggerAspect">
		<property name="operationNotification" ref="operationNotification"></property>
	</bean>

	
	

	<import resource="applicationContext-schedulers.xml" />
	<import resource="applicationContext-hdiv.xml" />
	
	<aop:aspectj-autoproxy />
</beans>

applicationContext-hdiv.xml


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
	<bean id="requestDataValueProcessor"
		class="org.springframework.security.web.servlet.support.csrf.CsrfRequestDataValueProcessor" />

	
	 <bean id="multipartResolver" class="org.hdiv.web.multipart.HdivCommonsMultipartResolver">
        
    </bean>
    
</beans>


hdiv-config.xml

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:hdiv="http://www.hdiv.org/schema/hdiv"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
       http://www.hdiv.org/schema/hdiv http://www.hdiv.org/schema/hdiv/hdiv.xsd">

    <hdiv:config excludedExtensions="css,png,gif,jpeg,jpg,js,ttf" errorPage="/manageMutation/security-error" maxPagesPerSession="10" confidentiality="true" strategy="memory" randomName="true"
   		avoidCookiesIntegrity="true" avoidCookiesConfidentiality="true" avoidValidationInUrlsWithoutParams="true" debugMode="true" showErrorPageOnEditableValidation="true" reuseExistingPageInAjaxRequest="true"> 
	    <hdiv:sessionExpired loginPage="/main/common" homePage="/"/>
		<hdiv:startPages method="get">/</hdiv:startPages>
		<hdiv:paramsWithoutValidation>
		</hdiv:paramsWithoutValidation>
		  <hdiv:longLivingPages>/</hdiv:longLivingPages>
	</hdiv:config>
	<hdiv:validation id="customValidation" componentType="text">
	    <hdiv:acceptedPattern><![CDATA[^[a-zA-Z0-9@.\-_]*$]]></hdiv:acceptedPattern>
	    <hdiv:rejectedPattern><![CDATA[(\s|\S)*(--)(\s|\S)*]]></hdiv:rejectedPattern>
	</hdiv:validation>
	<hdiv:editableValidations registerDefaults="true">
		<hdiv:validationRule url=".*" enableDefaults="false">customValidation</hdiv:validationRule>
	</hdiv:editableValidations>
</beans>

**Comment by pshah4u** [comment]
Hi Thanks for reply. Still not running at all given logs as

INFO: HDIV_PARAMETER_NOT_EXISTS;/Bhoomi/manageMutation/searchSurvey;1457468506;null;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser

My jsp has link as 

<a href="<spring:url value="/manageMutation/searchSurvey?ft=mp"/>">Link1</a>
<a href="<c:url value="/manageMutation/searchSurvey?ft=mp"/>">Link2</a>

webmvc-config.xml 

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aop="http://www.springframework.org/schema/aop"
	xmlns:task="http://www.springframework.org/schema/task"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd                 
http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd                 
http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.1.xsd
http://www.springframework.org/schema/aop 
http://www.springframework.org/schema/aop/spring-aop-3.1.xsd
http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task-3.0.xsd
">
	<task:annotation-driven />

	
	 
<mvc:annotation-driven validator="hdivEditableValidator"/>

	<context:property-placeholder location="WEB-INF/spring/*.properties" />

	
	<mvc:resources location="/, classpath:/META-INF/web-resources/"
		mapping="/resources/**" cache-period="${RESOURCE_CACHE_PERIOD}" />

	
	<mvc:default-servlet-handler />

	
	<mvc:interceptors>
		<bean class="org.springframework.web.servlet.theme.ThemeChangeInterceptor" />
		<bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"
			p:paramName="lang" />
	</mvc:interceptors>

	
	<mvc:view-controller path="/" view-name="index" />
	<mvc:view-controller path="/uncaughtException" />
	<mvc:view-controller path="/resourceNotFound" />
	<mvc:view-controller path="/dataAccessFailure" />

	
	<bean
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource"
		id="messageSource"
		p:basenames="classpath:com/accenture/bhoomi/resources/messages,WEB-INF/i18n/application"
		p:fallbackToSystemLocale="false" />

	
	<bean class="org.springframework.web.servlet.i18n.CookieLocaleResolver"
		id="localeResolver" p:cookieName="locale" />

	
	<bean
		class="org.springframework.ui.context.support.ResourceBundleThemeSource"
		id="themeSource" />

	
	<bean class="org.springframework.web.servlet.theme.CookieThemeResolver"
		id="themeResolver" p:cookieName="theme" p:defaultThemeName="standard" />

	
	<bean
		class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver"
		p:defaultErrorView="uncaughtException">
		<property name="exceptionMappings">
			<props>
				<prop key=".DataAccessException">dataAccessFailure</prop>
				<prop key=".NoSuchRequestHandlingMethodException">resourceNotFound</prop>
				<prop key=".TypeMismatchException">resourceNotFound</prop>
				<prop key=".MissingServletRequestParameterException">resourceNotFound</prop>
			</props>
		</property>
	</bean>

	
	
	<bean class="org.springframework.web.servlet.view.UrlBasedViewResolver"
		id="tilesViewResolver">
		<property name="viewClass"
			value="org.springframework.web.servlet.view.tiles2.TilesView" />
	</bean>
	<bean class="org.springframework.web.servlet.view.tiles2.TilesConfigurer"
		id="tilesConfigurer">
		<property name="definitions">
			<list>
				<value>/WEB-INF/layouts/layouts.xml</value>
				
				<value>/WEB-INF/views/**/views.xml</value>
			</list>
		</property>
	</bean>

	<context:annotation-config />
	<context:component-scan base-package="com.accenture.bhoomi" />
	<context:spring-configured />

	<bean id="logAspect" class="com.accenture.bhoomi.aspect.LoggerAspect">
		<property name="operationNotification" ref="operationNotification"></property>
	</bean>

	
	

	<import resource="applicationContext-schedulers.xml" />
	<import resource="applicationContext-hdiv.xml" />
	
	<aop:aspectj-autoproxy />
</beans>

applicationContext-hdiv.xml


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
	<bean id="requestDataValueProcessor"
		class="org.springframework.security.web.servlet.support.csrf.CsrfRequestDataValueProcessor" />

	
	 <bean id="multipartResolver" class="org.hdiv.web.multipart.HdivCommonsMultipartResolver">
        
    </bean>
    
</beans>


hdiv-config.xml

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:hdiv="http://www.hdiv.org/schema/hdiv"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
       http://www.hdiv.org/schema/hdiv http://www.hdiv.org/schema/hdiv/hdiv.xsd">

    <hdiv:config excludedExtensions="css,png,gif,jpeg,jpg,js,ttf" errorPage="/manageMutation/security-error" maxPagesPerSession="10" confidentiality="true" strategy="memory" randomName="true"
   		avoidCookiesIntegrity="true" avoidCookiesConfidentiality="true" avoidValidationInUrlsWithoutParams="true" debugMode="true" showErrorPageOnEditableValidation="true" reuseExistingPageInAjaxRequest="true"> 
	    <hdiv:sessionExpired loginPage="/main/common" homePage="/"/>
		<hdiv:startPages method="get">/</hdiv:startPages>
		<hdiv:paramsWithoutValidation>
		</hdiv:paramsWithoutValidation>
		  <hdiv:longLivingPages>/</hdiv:longLivingPages>
	</hdiv:config>
	<hdiv:validation id="customValidation" componentType="text">
	    <hdiv:acceptedPattern><![CDATA[^[a-zA-Z0-9@.\-_]*$]]></hdiv:acceptedPattern>
	    <hdiv:rejectedPattern><![CDATA[(\s|\S)*(--)(\s|\S)*]]></hdiv:rejectedPattern>
	</hdiv:validation>
	<hdiv:editableValidations registerDefaults="true">
		<hdiv:validationRule url=".*" enableDefaults="false">customValidation</hdiv:validationRule>
	</hdiv:editableValidations>
</beans>

**Comment by gillarramendi** [comment]
Try removing 'CsrfRequestDataValueProcessor' bean.
HDIV has its own 'RequestDataValueProcessor' implementation created automatically by <hdiv:config>.

**Comment by pshah4u** [comment]
Hi Thanks for reply.

Above configuration has been removed

now hdiv-config

<hdiv:config excludedExtensions="css,png,gif,jpeg,jpg,js,ttf" errorPage="/manageMutation/security-error" maxPagesPerSession="10" confidentiality="true" strategy="memory" randomName="true"
   		avoidCookiesIntegrity="true" avoidCookiesConfidentiality="true" avoidValidationInUrlsWithoutParams="true" debugMode="true" showErrorPageOnEditableValidation="true" reuseExistingPageInAjaxRequest="true"> 
	    <hdiv:sessionExpired loginPage="/main/common" homePage="/"/>
		<hdiv:startPages method="get">/,/.*</hdiv:startPages>
		<hdiv:paramsWithoutValidation>
		</hdiv:paramsWithoutValidation>
		  <hdiv:longLivingPages>/</hdiv:longLivingPages>
	</hdiv:config>

and logs coming as 
for first jsp:

INFO: HDIV_PARAMETER_NOT_EXISTS;/Bhoomi/getDropDown;255643103;null;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymous
Jan 13, 2015 10:09:08 AM org.hdiv.logs.Logger log
INFO: HDIV_PARAMETER_NOT_EXISTS;/Bhoomi/getSurveyList;255643103;null;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymous

Jan 13, 2015 10:09:12 AM org.hdiv.logs.Logger log
INFO: INVALID_CONFIDENTIAL_VALUE;/Bhoomi/manageMutation/addApplicantDetails;flowType;submitPartitionDetails;submitPartitionDetails;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymous
Jan 13, 2015 10:09:12 AM org.hdiv.logs.Logger log
INFO: INVALID_CONFIDENTIAL_VALUE;/Bhoomi/manageMutation/addApplicantDetails;district;30;[19, 17, 18, 15, 16, 13, 14, 11, 12, 21, 20, 22, 23, 24, 25, 26, 27, 28, 29, 3, 2, 10, 1, 30, 7, 6, 5, 4, 9, 8];0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser


Jan 13, 2015 10:09:12 AM org.hdiv.logs.Logger log
INFO: INVALID_CONFIDENTIAL_VALUE;/Bhoomi/manageMutation/addApplicantDetails;flowType;submitPartitionDetails;submitPartitionDetails;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymous
Jan 13, 2015 10:09:12 AM org.hdiv.logs.Logger log
INFO: INVALID_CONFIDENTIAL_VALUE;/Bhoomi/manageMutation/addApplicantDetails;district;30;[19, 17, 18, 15, 16, 13, 14, 11, 12, 21, 20, 22, 23, 24, 25, 26, 27, 28, 29, 3, 2, 10, 1, 30, 7, 6, 5, 4, 9, 8];0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymousUser

**Comment by amarewgs** [comment]
@gillarramendi where is that 'CsrfRequestDataValueProcessor' bean? plus I want the error page to be displayed if it fails on the editable validations.

<hdiv:config excludedExtensions="css,ico,js,woff,woff2,ttf,jpg,jpeg,png,gif,eot" avoidCookiesConfidentiality="true" avoidCookiesIntegrity="true" maxPagesPerSession="20" strategy="memory" avoidValidationInUrlsWithoutParams="true" reuseExistingPageInAjaxRequest="true"
                 errorPage="/secure/security-error" randomName="true" confidentiality="true" debugMode="true" showErrorPageOnEditableValidation="true">
        <hdiv:startPages>/auth/session-expired,/auth/logout,/auth/authentication-error,/index.jsp</hdiv:startPages>
        <hdiv:startPages method="get">/,/principal,/auth/principal,/j_spring_security_check</hdiv:startPages>
        <hdiv:startPages method="post">/principal,/auth/principal,/j_spring_security_check</hdiv:startPages>
    </hdiv:config>

    
    <hdiv:validation id="safeText">
        <hdiv:acceptedPattern><![CDATA[^[a-zA-Z0-9@.-_]*$]]></hdiv:acceptedPattern>
        
    </hdiv:validation>

    
    <hdiv:editableValidations registerDefaults="true">
        <hdiv:validationRule url="/secure/.*" enableDefaults="true">safeText</hdiv:validationRule>
        <hdiv:validationRule url="/secure/portfolios" parameters="firstName, lastName">safeText</hdiv:validationRule>
    </hdiv:editableValidations>

**Comment by gillarramendi** [comment]
The bean of type `CsrfRequestDataValueProcessor` is in the file `applicationContext-hdiv.xml `.
As I mentioned previously Hdiv has its own `RequestDataValueProcessor` implementation and `CsrfRequestDataValueProcessor` is overwriting it in the previous example.

If you want the error page to be displayed if it fails on the editable validations, it is enabled with the configuration property `showErrorPageOnEditableValidation `.
If it still doesn't work, be sure you are using Spring Mvc tags to create the form fields and you are enabling editable field validation for that url.
For example:

```xml
<hdiv:editableValidations>
	<hdiv:validationRule url="/.*"></hdiv:validationRule>
</hdiv:editableValidations>
```
