### ISSUE TITLE
Hibernate-validator Groups not working with HDIV

### ISSUE THREAD

**Issue by pshah4u** [hdiv/hdiv#70]
Hibernate-validator Groups group validation is not working with HDIV when i use "mvc:annotation-driven validator="hdivEditableValidator" instaed of "mvc:annotation-driven"

My implementing code in ManageBean is

@NotNull(groups = ApplicantValidation.class) private ApplicantBean applicantDetails;

and calling code in controller is

@Validated(ApplicantValidation.class) @Valid ManageBean manage

Please suggest if i am missing any required configuration.

**Comment by gillarramendi** [comment]
Hi, 
which version of HDIV are you using?
This was fixed in HDIV 2.1.7.

**Comment by pshah4u** [comment]
<hdiv.version>2.1.9</hdiv.version>

**Comment by gillarramendi** [comment]
Hi, 
yes, you were right! There was an issue in editable data validation and Spring MVC integration.
It is fixed now, look at this commit: https://github.com/hdiv/hdiv/commit/260d71714bd5c054b196bfecf2fc0914e24a303b

I have created a small sample (https://github.com/hdiv/hdiv-spring-mvc-showcase/tree/group-validation-sample) and it is working fine now.

Thank you!

**Comment by pshah4u** [comment]
Thanks, waiting for new version download
