### ISSUE TITLE
HDIV 2.1.4 and above does not generate _HDIV_STATE and throws IDataComposer not initialized on request, request is out of filter

### ISSUE THREAD

**Issue by dhinesherode91** [hdiv/hdiv#71]
I am using HDIV 2.1.0 in my application having spring MVC and Struts framework. I am using spring security also in my application.
HDIV 2.1.0 is working fine and it generates HDIV_STATE for all anchors and forms.

Now, I would like to upgrade to HDIV 2.1.4 and I have done that.
But now it doesn't generate the HDIV_STATE for any of the anchor tags and forms and when i checked in console it just shows,
 'DEBUG org.hdiv.urlProcessor.LinkUrlProcessor - IDataComposer not initialized on request, request is out of filter'.

I have configured my URLS for the HDIV Validator Filter in my web.xml and also the respective Hdiv Init Listener and the hdiv core tld. But still it does not generate the HDIV_STATE.

Am I missing anything(configuration) that is new in this HDIV update ?

Please share your thoughts.

Thanks in Advance.

**Comment by gillarramendi** [comment]
Some questions:
Do you use <hdiv:config> schema for configuration?
Which versions of Spring MVC and Struts do you have?
Which tld file do you include in your project? For Struts you need HDIV's tld file but for Spring MVC you have to use the one provided by Spring MVC.

**Comment by dhinesherode91** [comment]
Thanks for your reply..

>>>>>Do you use hdiv:config schema for configuration?
Yes, I am using hdiv:config schema for configuring start pages, start parameters, error pages in my hdiv-config.xml.

>>>>>Which versions of Spring MVC and Struts do you have?
Spring 3.2.x and Struts 1.3.8.

>>>>>For Struts you need HDIV's tld file but for Spring MVC you have to use the one provided by Spring MVC.
Yes, for struts I am using the hdiv-html.tld and hdiv-logic.tld that are provided by the HDIV and spring am using the spring.tld.

**Comment by gillarramendi** [comment]
Have you tried to modify ValidatorFilter mapping to match all requests?
For example:
```xml
<filter-mapping>
	<filter-name>ValidatorFilter</filter-name>
	<url-pattern>/*</url-pattern>
</filter-mapping>
```

**Comment by dhinesherode91** [comment]
Yes. It works and hdiv state is generated when we map the filter for all request.
Thanks for the help !!!

May be in future I will look into how we could generate the hdiv state based on specific request.
