### ISSUE TITLE
Could you please update project to use Spring's and hdiv's latest versions?

### ISSUE THREAD

**Issue by pashtika** [hdiv/hdiv#72]

**Comment by gillarramendi** [comment]
You mean https://github.com/hdiv/hdiv-spring-mvc-showcase project?

**Comment by gillarramendi** [comment]
Libraries updated: https://github.com/hdiv/hdiv-spring-mvc-showcase/commit/6e6b096350c31d90157db370ab1160104ec3d095

**Comment by pashtika** [comment]
Great !!  Thank you
