### ISSUE TITLE
When will hdiv-spring-hateoas be merged onto master?

### ISSUE THREAD

**Issue by george-y** [hdiv/hdiv#73]
Hi there

We've been experimenting with hdiv-spring-hateoas with great success. It has allowed us to secure our single page style web application against CSRF attacks (more benefits of hdiv to be investigated and added as we go along). 

Do you intend to merge the hdiv-spring-hateoas branch with master any time soon? As the module is not easily available through public maven repositories, for now we need to build and maintain the module internally. 

On a similar topic, do you have any information on what you plan to add to this module and when? :)

**Comment by fernandolozano** [comment]
Hi,
hdiv-spring-hateoas module supports only Link (GET method) resource processing, Form-like data (PUT/POST methods) processing is not completed and it is important to include all HDIV features.

Here the main problem is that there is not an standardized form data format for hateaos, there are several options like HTML form tags or custom JSON format.
This is something we want to investigate more and choose the best option.

**Comment by gillarramendi** [comment]
A convenient Hdiv and single page style applications integration is offered as part of Hdiv Enterprise Edition.
Have a look at this project to see how it is configured: https://github.com/hdiv/h4s-angularjs-springmvc-sample
And find more related resources in the link below:
https://hdivsecurity.com/resources
