### ISSUE TITLE
How to skip validation for post parameters in start page?

### ISSUE THREAD

**Issue by venkat75** [hdiv/hdiv#76]
Hi All,

I use the HDIV 2.1.9 version in our Spring MVC project with Handlebar templates.  I configured the HDIV validation and paramsWithoutValidation works fine once the HDIV session established.  In one scenario,  our application start page receive the post parameter which is in the xml format.  Simlar restfull server implementaion.  I defined that URL in hdiv:startPages and added that post parameter in hdiv:paramsWithoutValidation.  But it still validation happening.  I would like to skip the validation for start page post parameters. Can you please give some idea how can we do this?

**Comment by gillarramendi** [comment]
Hi, 
`startPage` and `paramsWithoutValidation` tags configure exclusions for parameter integrity validation.
What you need is to exclude some parameters from editable data validation (form text and textarea fields). This configuration is done in `<hdiv:editableValidations>` tag.

Example conf: https://github.com/hdiv/hdiv-spring-mvc-showcase/blob/master/src/main/webapp/WEB-INF/hdiv-config.xml#L21
More docs: http://www.hdiv.org/hdiv-documentation-single/doc.html#configuration-editabledata
