### ISSUE TITLE
HDIV error in forEach inside form select

### ISSUE THREAD

**Issue by VicCebedo** [hdiv/hdiv#77]
I'm having trouble trying to implement `form:select` in HDIV.
Here's my code in the JSP which renders the selector and options:

```html

    <form:form
    	modelAttribute="staffPosition" 
    	method="post"
    	action="${contextPath}/project/assign/staff">
    	<td>
    		<form:select class="form-control" path="staffID">
    			<c:forEach items="${staffList}" var="staff">
    				<c:set var="staffName" value="${staff.prefix} ${staff.firstName} ${staff.middleName} ${staff.lastName} ${staff.suffix}"/>
    				<form:option value="${staff.id}" label="${staffName}"/>
    			</c:forEach>
    		</form:select>
    	</td>
    	<td>
    		&nbsp;
    	</td>
    	<td>
    		<form:input placeholder="Example: Project Manager, Leader, etc..."
    			type="text"
    			class="form-control"
    			path="position"/>
    	</td>
    	<td>
    		&nbsp;
    	</td>
    	<td>
    		<button class="btn btn-default btn-flat btn-sm">Assign</button>
    	</td>
    </form:form>

```

After I click assign and initiate the action, the request would arrive in the `Controller` with the correct ID of the selected `form:option`.

```java

    public String assignStaff(
    	@ModelAttribute(ATTR_STAFF_POSITION) StaffAssignmentBean staffAssignment) {

```

However, when I inspected the console, there was an error:
`INVALID_CONFIDENTIAL_VALUE;/pmsys/project/assign/staff;staffID;27;[27, 28, 29, 30, 31, 32, 41];127.0.0.1;127.0.0.1;root`

When I tried to trace the line of code which spits out the error:
`org.hdiv.filter.ValidatorHelperRequest:948`

There was an inconsistency with the `originalValue` and the parameter `value` when this condition was evaluated:
`if (!m.matches() || (Integer.valueOf(value).intValue() >= stateValues.size())) {`

`originalValue` = [27, 28, 29, 30, 31, 32, 41]

`value` = 27 (This is the ID number of the `form:option` which I selected in the JSP)

Does anyone have any solution to this problem? Could this be a bug in HDIV?

**Note:**
This problem does not occur if I do not have a `<c:forEach` inside `<form:select`.

This is my **hdiv configuration**:

```xml

    <!-- *********************************************************** -->
    	<!-- *********************************************************** -->
    	<!-- HDIV ****************************************************** -->
    	<!-- *********************************************************** -->
    	<!-- *********************************************************** -->
    	<!-- HDIV Config -->
    	<beans:bean id="hdivEditableValidator" class="org.hdiv.web.validator.EditableParameterValidator"/>
    	<mvc:annotation-driven validator="hdivEditableValidator"/>
    	
    	<!-- Accepted pattern within the application for all editable parameters (generated from textbox and textarea) -->
    	<hdiv:validation id="safeText">
    		<hdiv:acceptedPattern><![CDATA[^[a-zA-Z0-9@.\-_]*$]]></hdiv:acceptedPattern>
    	</hdiv:validation>
    	
    	<hdiv:editableValidations>
    		<hdiv:validationRule url=".*" enableDefaults="false">safeText</hdiv:validationRule>
    	</hdiv:editableValidations>    
    	
    	<hdiv:config
    		debugMode="true"
    		errorPage="/fix"
    		excludedExtensions="css,png,gif,jpeg,jpg,js,woff,woff2,map"
    		randomName="true"
    		strategy="cipher">
    		<hdiv:sessionExpired loginPage="/auth/login" homePage="/"/>
    		
    		<!-- Controller calls that do not have validation -->
    		<hdiv:startPages>/</hdiv:startPages>
    		<hdiv:startPages method="get">/auth/denied,/fix,/,/auth/login,/auth/logout,/dashboard/,/image/display/project/profile/,/image/display/staff/profile/</hdiv:startPages>
    		<hdiv:startPages method="post">/j_spring_security_check</hdiv:startPages>
    	</hdiv:config>

```

The **WEB.XML**

```xml

    	<!-- Replace JSTL tld with HDIV tld-->
    	<jsp-config>
    	    <taglib>
    	        <taglib-uri>http://java.sun.com/jsp/jstl/core</taglib-uri>
    	        <taglib-location>/WEB-INF/tlds/hdiv-c.tld</taglib-location>
    	    </taglib>
    	</jsp-config>
    	
    	<!-- HDIV Listener -->
    	<listener>
    	    <listener-class>org.hdiv.listener.InitListener</listener-class>
    	</listener>
    	
    	<!-- HDIV Validator Filter -->
    	<filter>
    	    <filter-name>ValidatorFilter</filter-name>
    	    <filter-class>org.hdiv.filter.ValidatorFilter</filter-class>
    	</filter>
    	<filter-mapping>
    	    <filter-name>ValidatorFilter</filter-name>
    	    <servlet-name>appServlet</servlet-name>
    	</filter-mapping>

```

and **VERSIONS**

`<hdiv-version>2.1.9</hdiv-version>`

`<org.springframework>4.1.6.RELEASE</org.springframework>`

I have an outstanding question in Stackoverflow: http://stackoverflow.com/questions/29695093/hdiv-error-in-foreach-inside-form-select
Hopefully, someone here would be able to help me. Thank you very much.

**Comment by gillarramendi** [comment]
Hi, 
I have created a sample form in a branch called `option-foreach`:
https://github.com/hdiv/hdiv-spring-mvc-showcase/blob/option-foreach/src/main/webapp/WEB-INF/jsp/attacks/parameterTampering/SelectFieldTampering.jsp

It works fine for me with forEach iteration inside <form:select> tag.
Please try it in your environment and let me know
Regards

**Comment by VicCebedo** [comment]
Hi @gillarramendi 
Thank you very much for the reply. I have implemented my form in the same manner as what you've stated in the example.
However, it does not seem to work.

Below I have the getter function which is called when the page is loaded.
```java
String position = "";
long sampleID = 1;
StaffAssignmentBean saBean = new StaffAssignmentBean(sampleID, position);
// I have also tried setting:
// StaffAssignmentBean saBean = new StaffAssignmentBean();
// But still doesn't work.
model.addAttribute("staffPosition", saBean);
```

Actually I have here the complete source code of the controller:
https://github.com/VicCebedo/PracticeRepo/blob/master/projectroot/src/main/java/com/cebedo/pmsys/project/controller/ProjectController.java
Line: 714


Here, I have my form implemented the same way as stated in the example.
```html
<form:select class="form-control" path="staffID">
	<c:forEach items="${staffList}" var="staff">
		<c:set var="staffName" value="${staff.prefix} ${staff.firstName} ${staff.middleName} ${staff.lastName} ${staff.suffix}"/>
		<form:option value="${staff.id}" label="${staffName}"/>
	</c:forEach>
</form:select>
```
I also have the source code available here:
https://github.com/VicCebedo/PracticeRepo/blob/master/projectroot/src/main/webapp/WEB-INF/views/projectEdit.jsp
Line: 591


Hopefully, you would have the time to address my concern.
Thank you very much.

**Comment by gillarramendi** [comment]
Hi, 
Your application depends in a Dababase and JMS system and I can't run in my environment.
Please create a smaller sample application that shows the error case, otherwise I can't reproduce it.

Have you tried updating HDIV to the last release 2.1.10?

Regards

**Comment by VicCebedo** [comment]
Hi @gillarramendi 

I have created a very simple project and HDIV worked perfectly.
https://github.com/VicCebedo/PracticeRepo/tree/master/myHdivProblem

This proves that this problem is specific only to my application.

Thank you very much for you constant support.
I will contact again if I run into more problems in the future.
Thank you.
