### ISSUE TITLE
By-Pass HDIV Validation for an action URL when from a specific location but not from other locations.

### ISSUE THREAD

**Issue by dhinesherode91** [hdiv/hdiv#79]
Hi,

Im my application I am applying HDIV validation for particular action '/myapp/myaction' and it is working fine by doing the validations.

But when i access the same url action '/myapp/myaction' from one another part of my application, I just don't want the validation to be performed there.

Is it possible to perform so by doing something ?

Please share your thoughts.

Thanks in advance.

**Comment by fernandolozano** [comment]
It is not possible. We can not know the origin of the request.
