### ISSUE TITLE
HDIV Session Timeout Issue

### ISSUE THREAD

**Issue by venkat75** [hdiv/hdiv#80]
Hi All,
I am using HDIV 2.1.9 in Spring MVC application.  I configured the session timeout like this <hdiv:sessionExpired loginPage="/app/sessionTimeout" homePage="/"/> .  But I have to handle the session time out and implement some logic on session timed out. I handle the session timeout as part for Spring application event handler.  Now, the user logged in to the application and ideal in one page,  after session timed out, user selected any option in that page. The HDIV doesn't takes to the session timeout page.  It throws an error HDIV_PARAMETER_NOT_EXISTS; for the submitted page and redirected to system error page.  Because I configured the errorpage="/app/systemError" page.  It is not going into my event handler to handle the session time.  Before reaching that stage, it throws the HDIV error and redirected to error page.  Any idea, how to handle the session timeout and implement some logic at the time of session timed out.  This could be a common issue and is there any interception point available.  Really appreciate your help on this.

Thanks,
Venkatesan S.

**Comment by gillarramendi** [comment]
Hi, 
Session expire process is done in ```org.hdiv.filter.DefaultValidatorErrorHandler```class.
You can extend this class and add your custom behavior.

Configure the new ErrorHandler bean in your hdiv-config.xml file, for example:

```xml
<bean id="org.hdiv.filter.ValidatorErrorHandler" class="com.xxx.CustomValidatorErrorHandler">
      <property name="config" ref="org.hdiv.config.HDIVConfig" />
      <property name="userData" ref="org.hdiv.logs.IUserData" />
</bean>
```
I hope it helps

**Comment by venkat75** [comment]
Thanks for your update.  I tried the CustomValidatorErrorHandler and override the handleValidatorError method.  After session timeout, I got the error code HDIV_PARAMETER_NOT_EXISTS,  instead of PAGE_ID_INCORRECT.  Also the sesion is not consider as new.  So that not able to redirect to correct session time out page.  
In logs, after session timed out the below messages logged
INFO	HDIV's session destroyed:141CACC1BD0C3C294B9344584A3DCA92
INFO	HDIV's session created:12A2BF0ED7856DB76DAA4D9AF3371DBD
Then user click the page,  it goes to error page instead of sessionExpired page. the error displayed as INFO	HDIV_PARAMETER_NOT_EXISTS;/app/personalInfo;1618570988;null;10.132.108.82;10.132.108.82;anonymous

Can you please guide, how to trace the session timed out or not.

Thanks,
Venkatesan S.

**Comment by SimoneBernasconi1990** [comment]
Hello,
can I have more info? I have the same problem and I don't know how to solve it.
Thanks
