### ISSUE TITLE
Issue with AJAX & JQuery URL Param Values

### ISSUE THREAD

**Issue by msakethreddy** [hdiv/hdiv#81]
I am trying to integrate HDIV into my existing application. But I am stuck in solving the below problem.

Use Case: 1. I have a big form with huge number of fields. When I change a value in a drop down, I make an Ajax call by passing the selected value as a URL parameter. ex:

    $.get("http:://ajaxurl?dynamicParam=1", function(data) {/Render new HTML Content into existing page/});

    $.get("http:://ajaxurl?dynamicParam=2", function(data) {/Render new HTML Content into existing page**/}); etc.

Problem: As i select values in the drop down, different values are passed in the ajax param and HDIV throws an INVALID_PARAMETER_VALUE Error.

Only solution I can see is that I need to submit the whole Form with _MODIFIED_HDIV_STATE value.

But, I cant submit the whole form (Which has hell lot of data) in order to pass only one value as part of my Ajax call. Also, I cant exclude the param to bypass HDIV validation as I have the same use case across my application in numerous places.

Is there a way to pass the modified HDIV state as part of the AJAX call as we can do in the FORM submit ? Or please suggest me a way to solve this.

Please help me out to solve this issue. (I am stuck through half way after integrating HDIV into most of my application)

**Comment by fernandolozano** [comment]
Hi,

Your question has been answered in [StackOverflow](http://stackoverflow.com/questions/30147558/hdiv-how-to-modify-the-url-param-values-in-ajax-request/30348393#30348393). 

Best regards,
Fernando.
