### ISSUE TITLE
Adding HDIV State ID while making AJAX calls

### ISSUE THREAD

**Issue by prashathsenthil** [hdiv/hdiv#83]
Hi,

We have a Java based web application where we use HDIV as our security framework. Fundamentally our app does not have any form tags, rather we have many AJAX calls which brings JSON/HTML response with which the cards in the pages are constructed. 

We are making use of POST requests while dealing with sensitive data. Those data's are sent in POST request body. In order to be security compliant we do not include POST requests URL in the <hdiv:startPages> and if we do that we are getting HDIV related exceptions in our error log saying that "HDIV_PARAMETER_NOT_EXISTS;" we googled around and found that it is expecting the state ID and from these URL's (https://github.com/hdiv/hdiv/wiki/Appendix-C:-Ajax and https://github.com/hdiv/spring-mvc-showcase/blob/master/src/main/webapp/WEB-INF/views/partialform.jsp)we figured out how the HDIV state ID can be added for AJAX end points.

But the catch here is if the state ID is generated and appended as a query parameter to the AJAX end URL then HDIV is not throwing any exceptions since it identifies the state ID parameter from the end URL. On the other hand if we try to add the state ID in the request body then it throws the exception stating that the "HDIV_PARAMETER_NOT_EXISTS;". 

Precisely, 

1. We are not suppose to include POST request AJAX end point in <hdiv:startPages>
2. In order to do that we should append the state ID as part of the URL
3. That state ID should be in POST request body and not as a query parameter in the URL.

HDIV exception is thrown when state ID is in the request body and works only if it is available as a query parameter in the end point. For POST requests generally it is not recommended to add a parameter as a query string value.

It would be great if some one could guide us in this regard. 

Thanks!!!
Sai

**Comment by fernandolozano** [comment]
Hello,

If you do not use any form tags, HDIV does not notice about these data. You have to use form tags. Could you fix your issue?

**Comment by prashathsenthil** [comment]
Hello,

Our app is RESTful and there is no way to inject a form just for HDIV. I got a work around for this by adding the below code into the spring container.

<c:url var="someURL" value="/abc/show">
    <c:param name="_MODIFY_HDIV_STATE_" value="${hdivFormStateId}" />
</c:url>
<div data-url="${someURL}" id="someURL"></div>

The above div is referenced by this ID and the data-URL value is used while making POST requests.
