### ISSUE TITLE
sessionExpired set allowed session time

### ISSUE THREAD

**Issue by VicCebedo** [hdiv/hdiv#84]
Hi,

I have defined the sessionExpire like this and it works perfectly:
`<hdiv:sessionExpired loginPage="/auth/login/inactive" homePage="/"/>`

I would like to ask if there is any way to define the max allowed time of a session, maybe like this?
``<hdiv:sessionExpired loginPage="/auth/login/inactive" homePage="/" maxTime="600"/>``

If not, I would like to suggest a feature like that.
And I would also like to ask if what is the max time per session?

**Comment by gillarramendi** [comment]
Hi, 
you can configure a timeout for the session in the web.xml file:
For example 60 minutes:
<session-config>
        <session-timeout>60</session-timeout>
</session-config>

**Comment by VicCebedo** [comment]
Ok, you were very helpful. Thank you very much!
