### ISSUE TITLE
HDIV is giving INVALID_EDITABLE_VALUE though parameter mentioned in hdiv:paramswithoutvalidation

### ISSUE THREAD

**Issue by debojyotichatterjee** [hdiv/hdiv#85]
Hi,
I am using HDIV in my spring mvc app. There though I am mentioning the parameter names in hdiv:paramsWithoutValidation list, but for some very special characters (ex- % " < >)HDIV is interrupting & cancelling the request. The following status from the HDIV log I got:
Stripping jsessionid from url /abc/def/ajax/mailMethod
INVALID_EDITABLE_VALUE;/abc/def/ajax/mailMethod;customerAddress.addressLine1;%345;10.132.108.82;10.132.108.82;com.abc.def.domain.common.UserContext@104524d

But the criteria is, hdiv should not interrupt & we want the JSR 303 Validator to work on it.

Please let me know, if there is any way to avoid this issue.

Thanks,
Debo

**Comment by fernandolozano** [comment]
Hello,

If you have defined correctly the *hdiv:paramsWithoutValidation* it should not validate it. Could you show us your *hdiv:paramsWithoutValidation* configuration?

This can be an approach for your problem:

		<hdiv:paramsWithoutValidation>
			<hdiv:mapping url="/abc/def/ajax/mailMethod" parameters="customerAddress.addressLine1" />
		</hdiv:paramsWithoutValidation>

HDIV includes a default group of validation rules that try to avoid the most common risks such as XSS and SQL Injection. By default all editable fields of the request are validated.

I would recommend you not leaving without validation that field. You can define an *hdiv:editableValidations* disabling the default rules for that url and parameter and add a rule that suits you. And example:

	<hdiv:validation id="newRule" componentType="text">
		<hdiv:acceptedPattern><![CDATA[^[a-zA-Z0-9@.\-_]*$]]></hdiv:acceptedPattern>
		<hdiv:rejectedPattern><![CDATA[(\s|\S)*(--)(\s|\S)*]]></hdiv:rejectedPattern>
	</hdiv:validation>

    <hdiv:editableValidations>
		<hdiv:validationRule url="/abc/def/ajax/mailMethod" parameters="customerAddress.addressLine1" enableDefaults="false">newRule</hdiv:validationRule>
    </hdiv:editableValidations>

With HDIV 2.1.12 version you can see on the server's log which rule is stopping your request. 

I hope it helps
