### ISSUE TITLE
HDIV is giving INVALID cookie when a page is opening with an image

### ISSUE THREAD

**Issue by jchowdhary** [hdiv/hdiv#86]
HI , in my development, HDIV integrated with JSF is returning me a HDIV Error page with error as Invalid Cookie. This is happening when the page is trying to open an image.
how can i avoid this error so that my page is sucessfully loaded without this INVALID COOKIE error

**Comment by fernandolozano** [comment]
It seems that you are generating a cookie in the client side. As a result, HDIV does not notice about it.

Try disabling integrity in the cookies:

    <hdiv:config avoidCookiesIntegrity="true">

I hope it helps.
