### ISSUE TITLE
HDIV Schema Locations have disappeared from your website?

### ISSUE THREAD

**Issue by findhamid** [hdiv/hdiv#90]
Hi,

We would reference the following in our hdiv config file. 
http://www.hdiv.org/schema/hdiv http://www.hdiv.org/schema/hdiv/hdiv.xsd"
But they are now no longer available on your site and redirect to your homepage all of a sudden. Have they been moved somewhere?

Best regards,
Hamid

**Comment by fernandolozano** [comment]
Hello,

Thank you for your comment. They are available again on the same page: http://www.hdiv.org/schema/hdiv http://www.hdiv.org/schema/hdiv/hdiv.xsd"

Best regards,
Fernando

**Comment by martoncsukas** [comment]
Hi Fernando,

Was this just a one-off issue? I guess you have changed your website recently which caused the old website (and the XSD files) going down. 

Are you planning to keep XSD files there, and will the existing HDIV configurations remain compatible?

Many thanks,
Marton

**Comment by fernandolozano** [comment]
Hello Marton,

We are going to keep XSD files there. Do not worry, existing HDIV configurations will remain compatible.

Thank you for your interest.

Best regards,
Fernando
