### ISSUE TITLE
Getting cannot call getWriter() after getOutputStream error probably because of HDIV validation

### ISSUE THREAD

**Issue by HarishShukla** [hdiv/hdiv#91]
I am having a web application which is using HDIV, this application is implemented J2EE related technologies.
From a jsp I am sending a request to crystal report server to generate a report using crystal report viewer api. 
this code is working fine when I am not using HDIV, but when I am using hdiv then I am getting below error.

com.crystaldecisions.report.web.shared.WebReportingException: strict servlet API: cannot call getWriter() after getOutputStream()---- Error code:0

It seems like hdiv is doing some check and it is calling getOutputStream, because nowhere in my code I am using getOutputStream.

could someone please help me, what changes should I made in hdiv configuration or validation to resolve this error?

Thanks

**Comment by gillarramendi** [comment]
Hi, 
a lot of time have passed but any updates on this problem?

**Comment by gillarramendi** [comment]
I am going to close this issue. 
Feel free to reopen it if you have any update.
