### ISSUE TITLE
HDIV 3.2.0 error INVALID_COOKIE when domain is set

### ISSUE THREAD

**Issue by infoMatt** [hdiv/hdiv#92]
Using HDIV 3.2.0 + Spring 4 & Spring Security, the validation filter throws INVALID_COOKIE error if the SavedCookie (generated previously in the application) contains a _domain_ property.

Inside the isEqual method of SavedCookie there's an explicit comparison of Cookie _domain_, but that field is not sent by the browser (obviously).

### How to recreate:

- Enable cookie validation (cookie confidentiality doesn't matter)
- Create a cookie with a domain value set in a page
- Navigate to another page => INVALID_COOKIE error should be raised.

Thanks.

**Comment by fernandolozano** [comment]
Hello,

You were right. There was a problem in that specific case. It has been solved on this commit: https://github.com/hdiv/hdiv/commit/be7bb47773dbadbabddf856d008732600b9801ba

Thank you for your clear explanation,
Fernando
