### ISSUE TITLE
Spring+Thymeleaf+Jquery+HDIV

### ISSUE THREAD

**Issue by Chaitanya0315** [hdiv/hdiv#96]
We are building an application with Thymeleaf as presentation layer and Spring as the Service layer. Recently HDIV was integrated into the application.

Problem : A search page which takes in user input and displays results on the same page. This page uses Jquery to fetch the data from the backend in JSON format and bind the data to Jquery datatable.
The initial plan was to build the URL dynamically based on the input params to fetch the data, but since this wouldnt be possible with HDIV we tried an alternative of submitting a form with the data.
The Ajax form submit also fails with Unauthorized Execption although it has dynamically generated HDIV param associated with. What options are available for this situation?
Unfortunately the <c:out> or <spring:url> option for dynamically generating the url is ruled out in Thymeleaf.

**Comment by gillarramendi** [comment]
Hi,
if the form is rendered at server-side using Thymeleaf tags, you can send it using Ajax without any problem.
Form example using ```jQuery.serialize()``` function. 
Make sure all form fields are submitted and specially the _HDIV_STATE_ parameter.

**Comment by Chaitanya0315** [comment]
Most of the html element attributes are prefixed by th: - so the pages are rendered on the server side.A simple example of what is being tried ...

 <form th:action="@{~/******URL************}" th:id="submitForm">
	<div>
		input field with auto complete loaded from JQuery
	</div>
	<div>
		drop down list - select tags with data binding from Spring.
	</div>
 </form>
 
 JQUERY
 $.get($('#submitForm').attr('action'), $('#submitForm').serialize(), function () {
							//code
	})
	 .done(function (data) {
         //success
     })

The _HDIV_STATE parameter does get appended with the url from the form.serialize().
The error in the logs is related to the HTML elements within the form

o.hdiv.filter.ValidatorHelperRequest - Validation Error Detected: Parameter [html input element within the form] does not exist in the state for action [******URL*************]
org.hdiv.logs.Logger - INVALID_PARAMETER_NAME;*******URL*************;[html input element within the form];;;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;anonymous;

**Comment by gillarramendi** [comment]
Be sure you are creating all form field in server-side using thymeleaf tags.
For example:
```
<input type="text" th:field="*{firstName}" />
```
More examples in this project:
> https://github.com/hdiv/thymeleafexamples-petclinic/blob/2.1-master/src/main/webapp/WEB-INF/thymeleaf/owners/createOrUpdateOwnerForm.html#L56

**Comment by Chaitanya0315** [comment]
Thank you.
